### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by preese13** [jessamarie/this-day-in-history#38]
Hey Jessa, I opened the Heroku App and saw that none of my changes were active, then I forked and cloned the master branch and saw that the styling was different on Localhost 3000, but the functionality wasnt there.  Im trying to figure out what is going on but im struggling to parse through the App to figure out what needs to be done where

**Comment by jessamarie** [comment]
@preese13 

Our most recent changes are currently still on the development branch. I did not want to merge with master and redeploy until you were satisfied with the styling after I re-added the commenting feature and all of the events to the page.

Could you a `git checkout development` and then a `rails s` and see if you can view the changes from there? Let me know how it goes!

**Comment by jessamarie** [comment]
Just saw your recent merge comments! Lolol I'm sure we'll be fine. I was thinking of coming back to this one day and tackling an upgrade of some sort. Angular 1 is extremely outdated nowadays. 😅 Now that I think of it, did we ever get your final changes in after graduation??

Hope all is well @preese13!
